version: "3"

# You can also ask Task to include .env like files by using the dotenv: setting:
dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

# If `--` is given in the CLI, all following parameters are added to a special .CLI_ARGS variable.
# This is useful to forward arguments to another command.

tasks:

  check-config:
    desc: Check Hydra configuration
    cmds:
      - python vime/train.py --cfg all --resolve

  train:
    desc: Train a PyTorch model
    deps:
      - wandb
    cmds:
      - python vime/train.py -- {{.CLI_ARGS}}

  train-multi:
    desc: Launch multiple training jobs
    # Multirun launcher requires n_workers=0 otherwise it fails
    cmds:
      - python vime/train.py --multirun "dataloader.n_workers=0" -- {{.CLI_ARGS}}

  wandb:
    desc: Login to Weights & Biases
    cmds:
      - wandb login $WANDB_KEY
