_target_: pytorch_lightning.Trainer
max_epochs: 30
accelerator: mps
devices: 1
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: VIME
  save_dir: ${hydra:runtime.output_dir}
  log_model: True