model_summary:
  _target_: pytorch_lightning.callbacks.RichModelSummary

progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar
  refresh_rate: 5
  leave: True

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val-loss
  min_delta: 0.001
  patience: 5
  check_on_train_epoch_end: True

model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${hydra:runtime.output_dir}/checkpoints
  monitor: val-loss
  save_top_k: 1
  save_on_train_epoch_end: True
