encoder:
  lr: 0.01
  hidden_size: 128
  encoder_layers: 2
  pretext_layers: 2
  p_mask: 0.33
  alpha: 0.5

dataloader:
  _target_: vime.data.MnistData
  batch_size: 128
  n_workers: 10

optimizer:
  encoder:
    _target_: torch.optim.RMSprop
    _partial_: true
    lr: ${encoder.lr}

trainer:
  epochs: 10
  accelerator: mps
  devices: 1
